dashboard/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    re_path(r'^api/data/$', get_data, name="api_data"),
    re_path(r'^api/chart/data/$', ChartData.as_view()),
    path('order/', orderPage, name="order"),
    path('order/create/', addOrderPage, name="addOrders"),
    path('order/create/order_submission/',
         order_submission, name="order_submission"),
    path('order/<str:pk>/', detailedOrderPage, name="orderDetails"),
    path('order/<str:pk>/edit/', editOrder, name="editOrder"),
    path('order/<str:pk>/delete/', deleteOrder, name="deleteOrder"),
    path('order/<str:pk>/invoice/', ViewInvoice.as_view(), name="view_invoice"),
    path('order/<str:pk>/invoice/pdf', GeneratePDF.as_view(), name="invoice_pdf"),
]

homepage/urls.py
from django.urls import path, include

from register.views import registerPage
from homepage.views import homePage
from dashboard.views import dashboardPage
from signin.views import login_user, logout_user

urlpatterns = [
    path('', homePage, name="homepage"),
    path('register/', registerPage, name="register"),
    path('signin/', login_user, name="login"),
    path('logout_user', logout_user, name="logout"),
    path('dashboard/', dashboardPage, name="dashboard")
]

inventorytracker/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.views.static import serve

app_name = 'dashboard'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('dashboard/', include('dashboard.urls')),
]

dashboard/models.py
from django.db import models
from django import forms
from django.forms import widgets

#Form Layout from Crispy Forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

# Create your models here.

class Customer(models.Model):
    customer_name = models.CharField(
        max_length=255, default="unknown customer", blank=True)
    address = models.TextField('Address', max_length=255)
    phone_no = models.CharField(max_length=255, null=True)
    email_id = models.EmailField('Email', max_length=50)

    def __str__(self):
        return str(self.customer_name)


class Product(models.Model):
    product_name = models.CharField(max_length=255, null=True, blank=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    weight = models.CharField(max_length=255, null=True)
    quantity = models.IntegerField("Quantity")
    price = models.FloatField("Price", null=True)

    def __str__(self):
        return str(self.product_name)


class Vendor(models.Model):
    vendor_name = models.CharField(max_length=255, null=True, blank=True)
    email_id = models.EmailField('Email', max_length=50, null=True)

    def __str__(self):
        return str(self.vendor_name)


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Delivered', 'Delivered')
    )

    order_id = models.AutoField("Order_ID", primary_key=True)
    product = models.ManyToManyField(Product)
    customer = models.ForeignKey(
        Customer, null=True, on_delete=models.SET_NULL)
    vendor = models.ForeignKey(Vendor, null=True, on_delete=models.SET_NULL)
    date = models.DateField(null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    invoice_no = models.IntegerField("Invoice_No", unique=True, null=True)
    invoice = models.ImageField(null=True, blank=True)

    def __str__(self):
        return str(self.order_id)

dashboard/forms.py
from django.forms import ModelForm
from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

dashboard/views.py
from ast import Bytes
import random
from re import template
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib import messages
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from django.views import View
from xhtml2pdf import pisa
from django.http import JsonResponse

from rest_framework.views import APIView
from rest_framework.response import Response
from datetime import date
import random


# Create your views here.

def dashboardPage(request):
    order = Order.objects.all()

    order_count = Order.objects.count()
    print(order_count)

    delivered_order = Order.objects.filter(status="delivered")
    delivered_count = delivered_order.count()
    print(delivered_count)

    pending_order = Order.objects.filter(status="pending")
    pending_count = pending_order.count()
    print(pending_count)

    context = {'order': order, 'order_count': order_count, 'delivered_count': delivered_count, 'pending_count': pending_count}

    return render(request, 'dash.html', context)

def addOrderPage(request):
    return render(request, 'addOrder.html')

def order_submission(request):
    print("Form Data Submitted!")

    invoice_no = random.randint(1000, 9999)
    print(invoice_no)

    if request.method == 'POST':
        vendor = Vendor()
        vendor.vendor_name = request.POST.get('vendor-name')
        vendor.email_id = request.POST.get('vendor-email')
        vendor.save()

        product = Product()
        product.product_name = request.POST.get('item-name')
        product.category = request.POST.get('category')
        product.unit = request.POST.get('unit')
        product.quantity = request.POST.get('quantity')
        product.price = request.POST.get('price')
        product.save()

        cust = Customer()
        cust.customer_name = request.POST.get('cust-name')
        cust.phone_no = request.POST.get('phone-no')
        cust.email_id = request.POST.get('email-id')
        cust.address = request.POST.get('address')
        cust.save()

        order = Order()
        order.order_id = request.POST.get('order-id')
        order.date = request.POST.get('date')
        order.status = request.POST.get('status')
        order.invoice_no = invoice_no
        order.save()

        order.product.add(product)
        order.customer = cust
        order.vendor = vendor
        order.save()

        return redirect('dashboard:order')

    return render(request, 'addOrder.html')

def orderPage(request):
    context = {}

    order = Order.objects.all()
    context['order'] = order

    return render(request, 'order.html', context)

def detailedOrderPage(request, pk):
    context = {}
    
    order = Order.objects.get(order_id=pk)
    context['data'] = order
    context['products'] = order.product.all()

    return render(request, 'orderDetails.html', context)

def editOrder(request, pk):
    context = {}

    order = Order.objects.get(order_id=pk)
    context['data'] = order
    context['products'] = order.product.all()

    return render(request, 'edit.html', context)

def deleteOrder(request, pk):

    order = Order.objects.get(order_id=pk)
    products = order.product.all()
    cust = order.customer
    vend = order.vendor
    order.delete()
    products.delete()
    cust.delete()
    vend.delete()

    return redirect('dashboard:order')

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None

class ViewInvoice(View):

    def get(self, request, pk, *args, **kwargs):

        taxes = {
            "electronics": {
                "import_duty": "30%",
                "cgst": "19%",
                "handling_charges": "6%"
            },
            "chemicals": {
                "import_duty": "20%",
                "cgst": "5%",
                "handling_charges": "2%"
            },
            "hazardous chemicals": {
                "import_duty": "25%",
                "cgst": "12%",
                "handling_charges": "3%"
            },
            "automobiles": {
                "import_duty": "15%",
                "cgst": "18%",
                "handling_charges": "6%" 
            },
            "clothes": {
                "import_duty": "5%",
                "cgst": "5%",
                "handling_charges": "4%"
            },
        }

        context = {}
        template = get_template('invoice.html')
        order = Order.objects.get(order_id=pk)
        products = order.product.all()
        today = date.today()

        context["id"] = pk
        context["vendor_name"] = order.vendor
        context["vendor_email"] = order.vendor.email_id
        context["invoice"] = order.invoice_no
        context["name"] = order.customer
        context["phone"] = order.customer.phone_no
        context["address"] = order.customer.address
        context["date"] = today
        context["products"] = products

        for i in products:
            category = i.category

        # CALCULATE FINAL AMOUNT BY ADDING handling charges, import duty
        for key in list(taxes.keys()):
            if key == category:
                context["category"] = taxes.get(key)
                
        print(taxes.get(key))

        return render(request, "invoice.html", context)


class GeneratePDF(View):

    def get(self, request, pk, *args, **kwargs):

        context = {}
        taxes = {
            "electronics": {
                "import_duty": "30%",
                "cgst": "19%",
                "handling_charges": "6%"
            },
            "chemicals": {
                "import_duty": "20%",
                "cgst": "5%",
                "handling_charges": "2%"
            },
            "hazardous chemicals": {
                "import_duty": "25%",
                "cgst": "12%",
                "handling_charges": "3%"
            },
            "automobiles": {
                "import_duty": "15%",
                "cgst": "18%",
                "handling_charges": "6%" 
            },
            "clothes": {
                "import_duty": "5%",
                "cgst": "5%",
                "handling_charges": "4%"
            },
        }

        template = get_template('invoice.html')
        order = Order.objects.get(order_id=pk)
        products = order.product.all()
        today = date.today()

        context["id"] = pk
        context["vendor_name"] = order.vendor
        context["vendor_email"] = order.vendor.email_id
        context["invoice"] = order.invoice_no
        context["name"] = order.customer
        context["phone"] = order.customer.phone_no
        context["address"] = order.customer.address
        context["date"] = today
        context["products"] = products

        for i in products:
            category = i.category

        # CALCULATE FINAL AMOUNT BY ADDING handling charges, import duty
        for key in list(taxes.keys()):
            if key == category:
                context["category"] = taxes.get(key)

        html = template.render(context)
        pdf = render_to_pdf('invoicePdf.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'dash.html', {})


def get_data(request, *args, **kwargs):

    data = {
        "warehouse_space": "5000 sq.ft",
        "fixed_quantity": 30000
    }
    return JsonResponse(data)


class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        data = {}

        orders = Order.objects.all()

        for id in orders:
            order = Order.objects.get(order_id=id.order_id)
            data['order'] = order
            data['products'] = order.product.all()
            print(data)

        return Response(data)

dashboard/templates/addOrder.html
{% load static %}

<head>
  <title>{% block title %}Create Order{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static '/css/addorder.css' %}" />
</head>

{% block content %}
<div class="create-order">
  <form method="POST" action="order_submission/">
    {% csrf_token %}
    <div class="nav-order">
      <label id="create">CREATE ORDER</label>
      <div class="btns">
      <button type="submit" class="save">SAVE</button>
      <a href={% url 'dashboard:order' %} class="cancel">CANCEL</a>
      </div>
    </div>

    <div class="order-fields">
      <h2>ORDER INFORMATION</h2>
      <div class="inputs-field">
        <label><span>*</span>Order ID</label>
        <input type="text" class="box-text" name="order-id" required />
      </div>
      <div class="inputs-field">
        <label><span>*</span>Vendor Name</label>
        <input type="text" class="box-text" name="vendor-name" required />
      </div>
      <div class="inputs-field">
        <label><span>*</span>Vendor Email</label>
        <input type="email" class="box-text" name="vendor-email" required />
      </div>
      <div class="inputs-field">
        <label><span>*</span>Date</label>
        <input type="date" class="box-text" name="date" required />
      </div>
      <div class="inputs-field">
        <label for="status"><span>*</span>Status</label>
        <select name="status" class="box-text" name="status">
          <option value="pending">Pending</option>
          <option value="delivered">Delivered</option>
        </select>
      </div>
      <div class="inputs-field">
        <label><span>*</span>Order Bill</label>
        <input type="file" class="box-text" name="upload_bill" required />
      </div>
    </div>

    <div class="customer-fields">
      <h2>CUSTOMER INFORMATION</h2>
      <div class="inputs-field">
        <label><span>*</span>Customer Name</label>
        <input type="text" class="box-text" name="cust-name" required />
      </div>
      <div class="inputs-field">
        <label><span>*</span>Phone Number</label>
        <input type="text" class="box-text" name="phone-no" required />
      </div>
      <div class="inputs-field">
        <label><span>*</span>Email ID</label>
        <input type="email" class="box-text" name="email-id" required />
      </div>
      <div class="inputs-field">
        <label><span>*</span>Address</label>
        <input type="text" class="box-text" name="address" required />
      </div>
    </div>

    <div class="product-fields">
      <h2>ITEM LIST</h2>
      <div>
        <label><span>*</span>Item</label>
        <input type="text" class="box-text" name="item-name" required />
        <label><span>*</span>Weight</label>
        <select name="weight" class="box-text" name="weight">
          <option value="Kilogram">Kg</option>
        </select>
        <label><span>*</span>Quantity</label>
        <input type="number" class="box-text" name="quantity" required />
        <label><span>*</span>Price</label>
        <input type="text" class="box-text" name="price" required />
        <br /> 
        <label><span>*</span>Category</label>
        <select name="category" class="box-text" name="category">
          <option value="electronics">Electronics</option>
          <option value="chemicals">Chemicals</option>
          <option value="hazardous chemicals">Hazardous Chemicals</option>
          <option value="automobiles">Automobiles</option>
          <option value="clothes">Clothes</option>
        </select>
      </div>
    </div>
  </form>
</div>
{% endblock %}

dashboard/templates/chart.html
<head>
    <title>{% block title %}Dashboard{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
      crossorigin="anonymous">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
</head>


{% block jquery %}
<script>
  var endpoint = '/dashboard/api/data'

  $.ajax({
    method: "GET",
    url: endpoint,
    success: function(data) {
      console.log(data)
    },
    error: function(error_data){
      console.log("error")
      console.log(error_data)
    }
  })
</script>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm-12">
        <p>Items stored in the Warehouse</p>
        <div>
          
        </div>
        <canvas id="myChart" width="500" height="500"></canvas>
        <script>
            const ctx = document.getElementById('myChart').getContext('2d');
            const myChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: ['Electronics', 'Chemicals', 'Hazardous Chemicals', 'Automobiles', 'Clothes', 'Empty'],
                    datasets: [{
                        label: '# of Votes',
                        data: [12, 5, 3, 30, 20, 100],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(253, 202, 255, 0.2)',
                            'rgba(255, 200, 255, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: false,
                    maintainAspectRatio: true,
                    scales: {
                        
                    }
                }
            });
        </script>
    </div>
</div>

{% endblock %}

dashboard/templates/dash.html
{% load static %}

<head>
  <title>{% block title %}Dashboard{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">
  <link rel="stylesheet" href="{% static '/css/navdash.css' %}" />
  <link rel="stylesheet" href="{% static '/css/dash.css' %}" />
  <link rel="stylesheet" href="{% static '/css/home.css' %}" />
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>

{% block jquery %}
<script>
  var endpoint = '/dashboard/api/data'

  $.ajax({
    method: "GET",
    url: endpoint,
    success: function(data) {
      console.log(data)
    },
    error: function(error_data){
      console.log("error")
      console.log(error_data)
    }
  })
</script>
{% endblock %}


{% block content %}
<body>
  {% include 'navdash.html' %}
  <div class="main-dash">
    <div class="total-imports">
      <p>Total Imports</p>
      <p id="order_count">{{order_count}}</p>
    </div>
    <div class="imports-collected">
      <p>Current Imports</p>
      <p id="order_delivered">{{delivered_count}}</p>
    </div>
    <div class="imports-pending">
      <p>Pending Imports</p>
      <p id="order_pending">{{pending_count}}</p>
    </div>
    <div>
      {% include 'chart.html' %}
    </div>
  </div>
  <div class="space-orders">
    <div></div>
  <div class="space-orders container">
  </div>
  <div class="space-orders container">
    <div class="recent-orders">
      <h2>Recent Orders</h2>
      <div>
        <table>
          <tr>
            <th>Order ID</th>
            <th>Vendor</th>
            <th>Customer</th>
            <th>Date</th>
            <th>Status</th>
            <th>Invoice Number</th>
          </tr>
  
          {% for i in order %}
            <tr>
              <td><a href="/dashboard/order/{{i.order_id}}">{{i.order_id}}</a></td>
              <td>{{i.vendor}}</td>
              <td>{{i.customer}}</td>
              <td>{{i.date}}</td>
              <td class="status">
                <h6 class="{{i.status}}">{{i.status}}</h6>
              </td>
              <td>{{i.invoice_no}}</td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</body>
{% endblock %}

dashboard/templates/edit.html
{% block 'content' %}
<div>
    <h1>Edit Order</h1>
    <p>{{data.order_id}}</p>
</div>
{% endblock %}

dashboard/templates/invoice.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">
        <title>Invoice</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .wrapper {
                display: flex;
                flex-direction: row;
                align-items: center;
                justify-content: space-between;
            }
            td, th {
                font-weight: 600;
                text-align: center;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                color: #282828;
                display: flex;
            }
            .title {
                text-align: left;
                font-size: 22px;
                font-weight: 700;
                padding: 10px 20px 0px 20px;  
            }
            .date {
                text-align: right;
                font-size: 22px;
                font-weight: 100;
                margin-left: 100px;
                font-weight: 400;
                padding: 10px 20px 0px 20px;
            }
            .title span {
                color: #282828;
            }

            #print {
                text-decoration: none;
                padding: 10px;
                background-color: #007bff;
                color: white;
                font-size: 1rem;
                margin-right: 2rem;
                font-weight: 500;
                border-radius: 10px;
            }
            .vendor-customer {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                font-weight: 300;
                margin-top: 30px;
            }

            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                font-weight: 300;
                margin-left: 16.2vw;
                margin-top: 30px;
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Invoice #{{ invoice }}</p>
                <p class="date">Invoice Date : {{ date }}</p>
            </div>

            <a href="/dashboard/order/{{id}}/invoice/pdf" id="print">Print</a>
        </div>
        <div class="vendor-customer">
            <div class="vendor-details">
                Name: {{ vendor_name }}<br/>
                Email ID: {{ vendor_email }}<br/>
            </div>
            <div class='details'>
                Billed to <br />
                Name: {{ name }}<br/>
                Phone Number: {{ phone }}<br/>
                Address: {{ address }}
                <hr class='hrItem' />
            </div>
        </div>
        <div class="table">
            <table class="table">
                <tr>
                    <th>Item</th>
                    <th>Category</th>
                    <th>Weight</th>
                    <th>Qty</th>
                    <th>Amount</th>
                    <th>Handling Charges</th>
                    <th>Import Duty</th>
                    <th>CGST</th>
                    <th>Total Amount</th>
                </tr>

                <tr>
                    {% for prod in products %}
                       <td>{{ prod.product_name }}</td>
                       <td>{{ prod.category }}</td>
                       <td>{{ prod.weight }}</td>
                       <td>{{ prod.quantity }}</td>
                       <td>{{ prod.price }}</td>
                    {% endfor %}
                    <td>{{ category.handling_charges }}</td>
                    <td>{{ category.import_duty }}</td>
                    <td>{{ category.cgst }}</td>
                    <td>5000</td>
                </tr>
            </table>
        </div>
    </div>
    </body>
</html>

dashboard/templates/invoicePdf.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">
        <title>Invoice</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                color: #007cae;
                display: flex;
            }
            .title {
                text-align: left;
                font-size: 22px;
                font-weight: 100;
                padding: 10px 20px 0px 20px;  
            }
            .date {
                text-align: right;
                font-size: 22px;
                font-weight: 100;
                padding: 10px 20px 0px 20px;
            }
            td, th {
                text-align: center;
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Invoice #{{ invoice }}</p>
                <p class="date">Invoice Date : {{ date }}</p>
            </div>
        <div>
        <div class='details'>
            Billed to <br />
            Name: {{ name }}<br/>
            Phone Number: {{ phone }}<br/>
            Address: {{ address }}
            <hr class='hrItem' />
        </div>
        <div class="table">
            <table class="table">
                <tr>
                    <th>Item</th>
                    <th>Category</th>
                    <th>Qty</th>
                    <th>Amount</th>
                    <th>Handling Charges</th>
                    <th>Import Duty</th>
                    <th>CGST</th>
                    <th>Total Amount</th>
                </tr>

                <tr>
                    {% for prod in products %}
                       <td>{{ prod.product_name }}</td>
                       <td>{{ prod.category }}</td>
                       <td>{{ prod.quantity }}</td>
                       <td>{{ prod.price }}</td>
                    {% endfor %}
                    <td>{{ category.handling_charges }}</td>
                    <td>{{ category.import_duty }}</td>
                    <td>{{ category.cgst }}</td>
                    <td>5000</td>
                </tr>
            </table>
        </div>
    </div>
    </body>
</html>

dashboard/templates/navdash.html
{% load static %}

<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static '/css/navdash.css' %}" />
  <style type="text/css">
    body {
      font-weight: 200;
      font-size: 14px;
    }
    .links {
      display: flex;
      align-items: center;
      margin-left: 5vw;
    }
  </style>
</head>


{% block content %}
<div class="dash-navbar">
  <a href={% url 'homepage' %} id="logo">EasyInvent</a>
  <ul class="links">
    <li><a href={% url 'dashboard' %} id="dash">Dashboard</a></li>
    <li><a href={% url 'dashboard:order' %} id="order">Order</a></li>

    {% if user.is_authenticated %}
       <li class>
         <a href="{% url 'homepage' %}">Logout</a>
       </li>
    {% endif %}
  </ul>
</div>
{% endblock %}

dashboard/templates/order.html
{% load static %}

<head>
  <title>{% block title %}Orders{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static '/css/order.css' %}" />
</head>

{% block content %}
<div>
    {% include 'navdash.html' %}

    <div class="warehouse-order container">
      <h2 id="orders">Orders</h2>
      <hr />
      <div id="filters">
        <input type="text" name="order-id" placeholder="Search by id" class="id-text"/>
        <input type="date" name="order-date" class="date-input"/>

        <select name="status" name="status" class="options">
          <option value="pending">Pending</option>
          <option value="delivered">Delivered</option>
        </select>

      <div class="btns">
        <input type="button" value="Filter" class="btn-filter"/>
        <a href={% url 'dashboard:addOrders' %} class="add-orders">Create Order</a>
      </div>

      </div>

      <table>
        <tr>
          <th>Order ID</th>
          <th>Vendor</th>
          <th>Customer</th>
          <th>Date</th>
          <th>Status</th>
          <th>Invoice Number</th>
        </tr>

        {% for i in order %}
          <tr>
            <td><a href="/dashboard/order/{{i.order_id}}">{{i.order_id}}</a></td>
            <td>{{i.vendor}}</td>
            <td>{{i.customer}}</td>
            <td>{{i.date}}</td>
            <td class="status">{{i.status}}</td>
            <td>{{i.invoice_no}}</td>
            <td>{{i.product.price}}</td>
            <td><a href="/dashboard/order/{{i.order_id}}/edit">EDIT</a></td>
            <td><a href="/dashboard/order/{{i.order_id}}/delete">DELETE</a></td>
            <td><a href="/dashboard/order/{{i.order_id}}/invoice/">VIEW INVOICE</a></td>
          </tr>
        {% endfor %}
      </table>
    </div>
</div>
{% endblock %}